### ISSUE TITLE
Add Language translation support into Unifier

### ISSUE THREAD

**Issue by NullyIsHere** [UnifierHQ/unifier#145]
**Checklist**

- [x] The same feedback was not posted yet.
- [x] This is not a suggestion for the moderation team.
- [x] All info applicable to the issue has been attached.

**Is your feature request related to a problem? Please describe.**
I use Unifier self hosted in a Catalan, it would fit better all messages in catalan.

**Describe the solution you'd like**
LangMGR a system plugin that allows you to use new languages in Unifier.

**Describe alternatives you've considered**
*Only Google Translation but this way will have better quality,

**Additional context**

Related: https://github.com/UnifierHQ/unilang

**Comment by greeeen-dev** [comment]
Can you edit this to follow the template please?

**Comment by NullyIsHere** [comment]
> Can you edit this to follow the template please?

Done

**Comment by greeeen-dev** [comment]
@NullyIsHere I'm leaving you to finish translation support, I'll be working on adding more stuff to make external platform support better for Unifier

**Comment by greeeen-dev** [comment]
Decided to finish this myself, localization will be fully added very soon :) Shoutout to Copilot for taking care of a lot of of the tedious stuff I didn't want to do myself haha, definitely helped me save a lot of time doing this so I can spend more time on logic rather than replacing strings

Will release system language support on 3.4.1 and user language support on 3.4.2
